name: GoReleaser

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"

      - name: Clean dist directory
        run: rm -rf dist

      - name: Install Android NDK
        run: |
          mkdir -p $HOME/android-ndk
          curl -sSL https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -o ndk.zip
          unzip -q ndk.zip -d $HOME/android-ndk
          echo "$HOME/android-ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
